-*- mode: compilation; default-directory: "~/rpc25519/" -*-
Compilation started at Sat Jun  7 17:31:54

make rr2hr
go test -race -c -o rpc.test -count=1
rr record -h ./rpc.test -test.v -test.run Test04[05]
rr: Saving execution to trace directory `/mnt/oldrog/home/jaten/go/src/github.com/glycerine/rr_binary_for_issue74019/rr/rpc.test-43'.
faketime = false
=== RUN   Test040_remote_cancel_by_context

cli_test.go:948 [goID 8] 2025-06-07 22:31:55.913930083 +0000 UTC server Start() returned serverAddr = '127.0.0.1:41477'

cli.go:211 [goID 10] 2025-06-07 22:31:55.930197164 +0000 UTC connected to server 127.0.0.1:41477

cli_test.go:982 [goID 8] 2025-06-07 22:31:55.930478728 +0000 UTC cli_test 040: about to block on test040callStarted

cli_test.go:974 [goID 22] 2025-06-07 22:31:55.930869691 +0000 UTC client.Call() goro top about to call over net/rpc: MustBeCancelled.WillHangUntilCancel()
example.go:300 server-side: WillHangUntilCancel() is running

cli_test.go:984 [goID 8] 2025-06-07 22:31:57.133506033 +0000 UTC cli_test 040: we got past test040callStarted

cli_test.go:988 [goID 8] 2025-06-07 22:31:57.134168482 +0000 UTC past cancelFunc()

cli_test.go:977 [goID 22] 2025-06-07 22:31:57.135130509 +0000 UTC client.Call() returned with cliErr = 'cancellation request sent'

cli_test.go:991 [goID 8] 2025-06-07 22:31:57.135358543 +0000 UTC past cliErrIsSet channel; cliErr40 = 'cancellation request sent'

cli_test.go:998 [goID 8] 2025-06-07 22:31:57.135551219 +0000 UTC about to verify that server side context was cancelled.
example.go:304 net.rpc API: our net.Conn has 
local = '127.0.0.1:41477'
remote = '127.0.0.1:36276'
example.go:310 MustBeCancelled.WillHangUntilCancel(): ctx.Done() was closed!

cli_test.go:1000 [goID 8] 2025-06-07 22:31:57.137945256 +0000 UTC server side saw the cancellation request: confirmed.
example.go:324 server-side: MessageAPI_HangUntilCancel() is running
example.go:326: Message API: our net.Conn has local = '127.0.0.1:41477'; remote = '127.0.0.1:36276'

cli_test.go:1020 [goID 8] 2025-06-07 22:31:57.141043572 +0000 UTC cli_test 041: we got past test041callStarted

cli_test.go:1024 [goID 8] 2025-06-07 22:31:57.141242410 +0000 UTC past cancelFunc()

cli_test.go:1014 [goID 26] 2025-06-07 22:31:57.142272766 +0000 UTC client.Call() returned with cliErr = 'cancellation request sent'

cli_test.go:1027 [goID 8] 2025-06-07 22:31:57.142471394 +0000 UTC past cliErrIsSet channel; cliErr = 'cancellation request sent'

cli_test.go:1038 [goID 8] 2025-06-07 22:31:57.142668218 +0000 UTC about to verify that server side context was cancelled.
example.go: MustBeCancelled.MessageAPI_HangUntilCancel(): ctx.Done() was closed!

0 assertions thus far

--- PASS: Test040_remote_cancel_by_context (1.24s)
=== RUN   Test045_upload

cli.go:1473 [goID 10] 2025-06-07 22:31:57.154899332 +0000 UTC rpc: client protocol error: 'shutting down'

srv.go:585 [goID 14] 2025-06-07 22:31:57.157980745 +0000 UTC server sees io.EOF from receiveMessage

cli.go:211 [goID 31] 2025-06-07 22:31:57.175681219 +0000 UTC connected to server 127.0.0.1:44399
ThreadSanitizer: CHECK failed: tsan_sync.cpp:95 "((0)) != (0)" (0x0, 0x0) (tid=2466046)
make: *** [Makefile:62: rr2hr] Error 66

Compilation exited abnormally with code 2 at Sat Jun  7 17:31:57

rr: Packed trace directory `/mnt/oldrog/home/jaten/go/src/github.com/glycerine/rr_binary_for_issue74019/rr/rpc.test-43'.
