faketime = false
=== RUN   Test040_remote_cancel_by_context

cli_test.go:948 [goID 34] 2025-06-09 01:42:49.120092533 +0000 UTC server Start() returned serverAddr = '127.0.0.1:46777'

cli.go:211 [goID 23] 2025-06-09 01:42:49.144596666 +0000 UTC connected to server 127.0.0.1:46777

cli_test.go:982 [goID 34] 2025-06-09 01:42:49.145128426 +0000 UTC cli_test 040: about to block on test040callStarted

cli_test.go:974 [goID 8] 2025-06-09 01:42:49.145315972 +0000 UTC client.Call() goro top about to call over net/rpc: MustBeCancelled.WillHangUntilCancel()

cli_test.go:984 [goID 34] 2025-06-09 01:42:50.263618463 +0000 UTC cli_test 040: we got past test040callStarted

cli_test.go:988 [goID 34] 2025-06-09 01:42:50.263840124 +0000 UTC past cancelFunc()
example.go:300 server-side: WillHangUntilCancel() is running
example.go:304 net.rpc API: our net.Conn has 
local = '127.0.0.1:46777'
remote = '127.0.0.1:32914'
example.go:310 MustBeCancelled.WillHangUntilCancel(): ctx.Done() was closed!

cli_test.go:977 [goID 8] 2025-06-09 01:42:50.265722409 +0000 UTC client.Call() returned with cliErr = 'cancellation request sent'

cli_test.go:991 [goID 34] 2025-06-09 01:42:50.267082252 +0000 UTC past cliErrIsSet channel; cliErr40 = 'cancellation request sent'

cli_test.go:998 [goID 34] 2025-06-09 01:42:50.267363106 +0000 UTC about to verify that server side context was cancelled.

cli_test.go:1000 [goID 34] 2025-06-09 01:42:50.267563356 +0000 UTC server side saw the cancellation request: confirmed.
example.go:324 server-side: MessageAPI_HangUntilCancel() is running
example.go:326: Message API: our net.Conn has local = '127.0.0.1:46777'; remote = '127.0.0.1:32914'

cli_test.go:1020 [goID 34] 2025-06-09 01:42:50.269248277 +0000 UTC cli_test 041: we got past test041callStarted

cli_test.go:1024 [goID 34] 2025-06-09 01:42:50.269440902 +0000 UTC past cancelFunc()
example.go: MustBeCancelled.MessageAPI_HangUntilCancel(): ctx.Done() was closed!

cli_test.go:1014 [goID 39] 2025-06-09 01:42:50.271182991 +0000 UTC client.Call() returned with cliErr = 'cancellation request sent'

cli_test.go:1027 [goID 34] 2025-06-09 01:42:50.271379765 +0000 UTC past cliErrIsSet channel; cliErr = 'cancellation request sent'

cli_test.go:1038 [goID 34] 2025-06-09 01:42:50.271586417 +0000 UTC about to verify that server side context was cancelled.

0 assertions thus far

--- PASS: Test040_remote_cancel_by_context (1.16s)
=== RUN   Test045_upload

cli.go:1473 [goID 23] 2025-06-09 01:42:50.274758423 +0000 UTC rpc: client protocol error: 'shutting down'

srv.go:585 [goID 27] 2025-06-09 01:42:50.275047812 +0000 UTC server sees io.EOF from receiveMessage

srv.go:1120 [goID 40] 2025-06-09 01:42:50.279392956 +0000 UTC sendMessage got err = 'use of closed network connection'; on trying to send Seqno=4

cli.go:211 [goID 30] 2025-06-09 01:42:50.296252238 +0000 UTC connected to server 127.0.0.1:40073

cli.go:2718 [goID 28] 2025-06-09 01:42:51.121739634 +0000 UTC no simnet, Client made time.NewTimer(dur=1m0s)
...
3 assertions thus far

--- PASS: Test045_upload (1.17s)
PASS
